### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Zhyus** [vikiboss/deno-functions#1]
Multiple requests for different results.Normal request:
![image](https://github.com/vikiboss/deno-functions/assets/32297307/b3e60f9c-6f4d-4bd5-b4d3-82f26a1e7dd7)
bad request:(This error recurs steadily)
![image](https://github.com/vikiboss/deno-functions/assets/32297307/b76663ce-cbe3-4afb-91a7-ded62bb5027a)

**Comment by vikiboss** [comment]
Now, it has been fixed.

<img width="795" alt="image" src="https://github.com/vikiboss/deno-functions/assets/53367348/3fbc6dd9-fa7c-4521-a3af-c2508d95733f">
