### ISSUE TITLE
[Bug] Only abstract of item page is fetched

### ISSUE THREAD

**Issue by voyager0003** [vikiboss/deno-functions#2]
for example:
the return of https://baike.deno.dev/item/qihuo:
```json
{
"status":200,
"message":"OK",
"data":{
"itemName":"期货市场",
"description":"期货市场，是按达成的协议交易并按预定日期交割的金融市场。现货与期货的显著区别是，期货的交割期放在未来，而价格、交货及付款的数量、方式、地点和其他条件是在即期由买卖双方在合同中规定的，商品及证券均可在期货市场上交易。虽然合同已经签订，但双方买卖的商品可能正在运输途中，也可能正在生产中，甚至可能还没有投入生产过程，卖者手中可能有商品或证券，也可能没有商品或证券。2021年全国期货市场累计成交量约为75.14亿手，累计成交额约为581.20万亿元，同比分别增长22.13%和32.84%。",
"cover":"https://bkimg.cdn.bcebos.com/pic/b3fb43166d224f4a96473f8203f790529922d141?x",
"link":"https://baike.baidu.hk/item/%E6%9C%9F%E8%B4%A7%E5%B8%82%E5%9C%BA/970728","updateTime":"2023-12-20 13:37:15"}
}
```
but the source page has more infomation, and many content is missing:
https://baike.baidu.hk/item/%E6%9C%9F%E8%B4%A7%E5%B8%82%E5%9C%BA/970728

screenshot of source page:
![screenshot of source page](https://github.com/vikiboss/deno-functions/assets/15920086/6b83cf2c-3004-49ff-9134-0ba97e6dae40)

**Comment by vikiboss** [comment]
This is as expected, it only returns the brief abstract, and it expects the user to access the full details via the return link.

**Comment by voyager0003** [comment]
I got it. Thanks for your great working of the baike api.
